version: '3'
services:
  todotests:
  image: todotests
  depends_on:
  - todoback 
  - todofrontend
  environment: 
  - FRONT_HOST=frontend
  # restart: always

  todofront:
    image: todofrontend
    ports:
      - 3000:3000
    depends_on:
       - todoback
    environment:
      - REACT_APP_API_HOST=todoback

  todoback:
    image: todobackend
    ports: 
    - 3001:3001